apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetic-retinopathy-model-service
  labels:
    app: diabetic-retinopathy-model-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: diabetic-retinopathy-model-service
  template:
    metadata:
      labels:
        app: diabetic-retinopathy-model-service
    spec:
      containers:
        - name: diabetic-retinopathy-model-service
          image: xuanduck/diabetic-retinopathy-model-service:1.0.0 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: diabetic-retinopathy-model-service
spec:
  selector:
    app: diabetic-retinopathy-model-service
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8001
